modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
[[mods]]
modId="rm"
version="0.1"
displayName="Revive Mod"
authors="DDR"
description='''
Это мод добавляющий свитки возрождения, что позволят вам возродить своего умершего друга в режиме хардкора.

Этот мод создан для сетевой игры и не подходит для одиночной компании.
'''
displayURL="https://github.com/DrZoidberg813"
logoFile="revive_scroll.png"
[[dependencies.rm]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
